.TH "/home/finlay/RTEP1/Rpi_end/200322_Rpi_end_together Directory Reference" 3 "Sat Apr 18 2020" "Muscle Power Gaming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/finlay/RTEP1/Rpi_end/200322_Rpi_end_together Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBads1115\&.cpp\fP"
.br
.RI "Sets the ADS1115 to the correct configurations and operates accordingly\&. "
.ti -1c
.RI "file \fBads1115\&.h\fP"
.br
.RI "Defines a set of macros for use in configuring the ADS1115 and a class for controlling the configured device\&. "
.ti -1c
.RI "file \fBGPIOlis\&.cpp\fP"
.br
.RI "Controls the interupt and threading features of the signal reading\&. "
.ti -1c
.RI "file \fBGPIOlis\&.h\fP"
.br
.RI "A collection of useful C++ classes for use of an ADS1115 device in UDP transmission and an Android Pong game\&. "
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBwindow\&.cpp\fP"
.br
.RI "Stuff\&. "
.ti -1c
.RI "file \fBwindow\&.h\fP"
.br
.RI "Provides the framework for the production of the GUI window for the EMG controlled Pong game\&. "
.in -1c
