.TH "/home/finlay/RTEP1/Server_end/Server_Pong_GUI_all_together Directory Reference" 3 "Sun Apr 19 2020" "Muscle Power Gaming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/finlay/RTEP1/Server_end/Server_Pong_GUI_all_together Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmainwindow\&.cpp\fP"
.br
.RI "Realisation of the EMG-controlled Pong GUI\&. "
.ti -1c
.RI "file \fBmainwindow\&.h\fP"
.br
.RI "Produces the GUI window from which the EMG-controlled Pong game can be played\&. "
.in -1c
