.TH "cmdmtx" 3 "Sat Apr 18 2020" "Muscle Power Gaming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmdmtx \- Allows multiple threads to share the same resource\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Allows multiple threads to share the same resource\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Muscle Power Gaming from the source code\&.
