.TH "group7" 3 "Sun Apr 19 2020" "Muscle Power Gaming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
group7 \- ADS1115 Bit[7-5]\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBADS1115_REG_CONFIG_DR_8SPS\fP   (0x0000)"
.br
.RI "8 samples per second "
.ti -1c
.RI "#define \fBADS1115_REG_CONFIG_DR_16SPS\fP   (0x0020)"
.br
.RI "16 samples per second "
.ti -1c
.RI "#define \fBADS1115_REG_CONFIG_DR_32SPS\fP   (0x0040)"
.br
.RI "32 samples per second "
.ti -1c
.RI "#define \fBADS1115_REG_CONFIG_DR_64SPS\fP   (0x0060)"
.br
.RI "64 samples per second "
.ti -1c
.RI "#define \fBADS1115_REG_CONFIG_DR_128SPS\fP   (0x0080)"
.br
.RI "128 samples per second "
.ti -1c
.RI "#define \fBADS1115_REG_CONFIG_DR_250SPS\fP   (0x00A0)"
.br
.RI "250 samples per second (DEFAULT) "
.ti -1c
.RI "#define \fBADS1115_REG_CONFIG_DR_475SPS\fP   (0x00C0)"
.br
.RI "475 samples per second "
.ti -1c
.RI "#define \fBADS1115_REG_CONFIG_DR_860SPS\fP   (0x00E0)"
.br
.RI "860 samples per second "
.in -1c
.SH "Detailed Description"
.PP 
ADS1115 Bit[7-5]\&. 

These bits control the data rate setting\&.
.IP "\(bu" 2
8 sps
.IP "\(bu" 2
16 sps
.IP "\(bu" 2
32 sps
.IP "\(bu" 2
64 sps
.IP "\(bu" 2
128 sps
.IP "\(bu" 2
250 sps
.IP "\(bu" 2
475 sps
.IP "\(bu" 2
860 sps
.PP
The DEFAULT data rate is 250 samples per second\&. 
.SH "Macro Definition Documentation"
.PP 
.SS "#define ADS1115_REG_CONFIG_DR_128SPS   (0x0080)"

.PP
128 samples per second 
.PP
Definition at line 273 of file ads1115\&.h\&.
.SS "#define ADS1115_REG_CONFIG_DR_16SPS   (0x0020)"

.PP
16 samples per second 
.PP
Definition at line 270 of file ads1115\&.h\&.
.SS "#define ADS1115_REG_CONFIG_DR_250SPS   (0x00A0)"

.PP
250 samples per second (DEFAULT) 
.PP
Definition at line 274 of file ads1115\&.h\&.
.SS "#define ADS1115_REG_CONFIG_DR_32SPS   (0x0040)"

.PP
32 samples per second 
.PP
Definition at line 271 of file ads1115\&.h\&.
.SS "#define ADS1115_REG_CONFIG_DR_475SPS   (0x00C0)"

.PP
475 samples per second 
.PP
Definition at line 275 of file ads1115\&.h\&.
.SS "#define ADS1115_REG_CONFIG_DR_64SPS   (0x0060)"

.PP
64 samples per second 
.PP
Definition at line 272 of file ads1115\&.h\&.
.SS "#define ADS1115_REG_CONFIG_DR_860SPS   (0x00E0)"

.PP
860 samples per second 
.PP
Definition at line 276 of file ads1115\&.h\&.
.SS "#define ADS1115_REG_CONFIG_DR_8SPS   (0x0000)"

.PP
8 samples per second 
.PP
Definition at line 269 of file ads1115\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Muscle Power Gaming from the source code\&.
