.TH "group9" 3 "Sun Apr 19 2020" "Muscle Power Gaming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
group9 \- ADS1115 Bit[3]\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBADS1015_REG_CONFIG_CPOL_ACTVLOW\fP   (0x0000)"
.br
.RI "ALERT/RDY pin is active low (DEFAULT) "
.ti -1c
.RI "#define \fBADS1015_REG_CONFIG_CPOL_ACTVHI\fP   (0x0008)"
.br
.RI "ALERT/RDY pin is active high\&. "
.in -1c
.SH "Detailed Description"
.PP 
ADS1115 Bit[3]\&. 

This bit controls the polarity of the ALERT/RDY pin\&.
.PP
The DEFAULT setting holds the ALERT/RDY pin active low 
.SH "Macro Definition Documentation"
.PP 
.SS "#define ADS1015_REG_CONFIG_CPOL_ACTVHI   (0x0008)"

.PP
ALERT/RDY pin is active high\&. 
.PP
Definition at line 310 of file ads1115\&.h\&.
.SS "#define ADS1015_REG_CONFIG_CPOL_ACTVLOW   (0x0000)"

.PP
ALERT/RDY pin is active low (DEFAULT) 
.PP
Definition at line 309 of file ads1115\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Muscle Power Gaming from the source code\&.
