.TH "/home/finlay/RTEP1/Server_end/Server_Pong_GUI_all_together/main.cpp" 3 "Sun Apr 19 2020" "Muscle Power Gaming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/finlay/RTEP1/Server_end/Server_Pong_GUI_all_together/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <QApplication>\fP
.br
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include <QScreen>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"
The \fCmain\fP function is used to find and update the mainwindow with the optimum screen and display size for android applications using \fBQt\fP 
.PP
Definition at line 10 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Muscle Power Gaming from the source code\&.
