.TH "md__home_finlay__r_t_e_p1__rpi_end_200322__rpi_end_together__r_e_a_d_m_e" 3 "Sat Apr 18 2020" "Muscle Power Gaming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_finlay__r_t_e_p1__rpi_end_200322__rpi_end_together__r_e_a_d_m_e \- README 
Unit-tested: rpi end code together
.PP
This is the work sample for raspberryPi+ads1115 of all rpi end code together, including: ads driver thread monitering gpio interrupt rt plot iir power time smooth internet sending (UDP) unit test video https://www.youtube.com/watch?v=j-3AxjxNN2I https://www.youtube.com/watch?v=jThJus-PdIQ 
