.TH "Ui" 3 "Sun Apr 19 2020" "Muscle Power Gaming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui \- Defines a namespace for declaration of window functions specific to the game GUI\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Defines a namespace for declaration of window functions specific to the game GUI\&. 

This namespace acts to provide segmentation between functions defined purely within the scope of the game GUI from those outwith\&. Strictly contains the \fBMainWindow\fP{} class and it's members\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Muscle Power Gaming from the source code\&.
