.TH "/home/finlay/RTEP1/Rpi_end/Rpi_end_together/window.h" 3 "Sun Apr 19 2020" "Muscle Power Gaming" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/finlay/RTEP1/Rpi_end/Rpi_end_together/window.h \- Provides the framework for the production of the GUI window for the EMG controlled Pong game\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <qwt/qwt_thermo\&.h>\fP
.br
\fC#include <qwt/qwt_knob\&.h>\fP
.br
\fC#include <qwt/qwt_plot\&.h>\fP
.br
\fC#include <qwt/qwt_plot_curve\&.h>\fP
.br
\fC#include <QBoxLayout>\fP
.br
\fC#include <QUdpSocket>\fP
.br
\fC#include <QTimer>\fP
.br
\fC#include <QWidget>\fP
.br
\fC#include <Iir\&.h>\fP
.br
\fC#include 'ads1115\&.h'\fP
.br
\fC#include 'GPIOlis\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWindow\fP"
.br
.RI "Generates and updates the components of the Pong game's GUI window\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provides the framework for the production of the GUI window for the EMG controlled Pong game\&. 

Defines the \fBWindow\fP class, responsible for producing and updating the game GUI based on the incoming EMG signal\&.
.PP
\fBAuthor\fP
.RS 4
Zonghan Gan 
.PP
Finlay Nelson 
.PP
Henry Cowan 
.RE
.PP
\fBDate\fP
.RS 4
11 April 2020 
.RE
.PP

.PP
Definition in file \fBwindow\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Muscle Power Gaming from the source code\&.
